### ISSUE TITLE
Does this work with fixed target speaker without parallel data?

### ISSUE THREAD

**Issue by abhilashi** [albertaparicio/tfg-voice-conversion#1]

**Comment by albertaparicio** [comment]
Dear abhilashi,

First and foremost, thank you for your interest in my project.

Regarding your question, If by "without parallel data", you mean that the source's speech and the target's speech used in training do not represent the same uttered words, then the system will not work well.

The system relies on a parallel data set to learn the feature mapping from the source speaker to the target speaker.

I hope I have answered your question meaningfully. If you have any more doubts, do not hesitate to ask.

Respectfully,

Albert
