### ISSUE TITLE
What is or where is ”interpolate.py“？

### ISSUE THREAD

**Issue by HudsonHuang** [albertaparicio/tfg-voice-conversion#2]
Thank you for your great work.
And，
I run data/training/seq2seq_align_training.sh . And got an error showing that it needs a interpolate.py which is not in my system. Could u show me how to get the interpolate.py？

Here is the code in data/training/seq2seq_align_training.sh：
        _# Interpolate lfo and vf data
        python $(which interpolate.py) \
            --f0_file ${DIR_VOC}/${DIR_SPK}/${FILENAME}.lf0.dat \
            --vf_file ${DIR_VOC}/${DIR_SPK}/${FILENAME}.vf.dat \
            --no-uv_

run with error of：
_Processing SM2/200040
Unknown option: --
usage: python [option] ... [-c cmd | -m mod | file | -] [arg] ...
Try `python -h' for more information._

I search for interpolate.py and found scipy has such a file ,but without parameter of f0_file vf_file and no-uv_ 
how to get the code work?THX

**Comment by albertaparicio** [comment]
Dear @HudsonHuang ,
The interpolate.py file belongs to the ahoproc-tools repository:
https://github.com/santi-pdp/ahoproc_tools/blob/master/ahoproc_tools/interpolate.py
Originally, I put it in a folder of my $PATH

**Comment by HudsonHuang** [comment]
It works，thank you so much!
